build: use node 10 or superior
simonepri/pidtree pull request #12
Opened 2021-01-11 15:55 UTC by Kikobeats

2021-01-11 16:20 UTC, huan approved these changes
LGTM

2021-01-11 16:30 UTC, Kikobeats commented
not sure why windows builds are failing, probably is related to a thing not related with this PR  🤔

2021-01-12 10:03 UTC, simonepri commented
Thanks for contributing!

At the moment this DLGTM.
I think is appropriate to bump the package to a stable before dropping support for node 0.10 (altough we don't have the CI testing it, it is still supported).

Before doing this though, I need to improve the CI and find a way to test on more OS than we currently do (maybe using a mixure of vagrant and docker, suggestions welcome).

2021-01-12 10:15 UTC, Kikobeats commented
@simonepri I agree, right now CI build is a problem.

What if we delay this to be shipped under `1.0.0` version? 

Then both things could be done: If you need to use Node 10 or lower, use 0.x, otherwise 1.x is for you.

2021-01-12 10:46 UTC, simonepri commented
Yes that's exactly the plan!

The PR per se looks good, it is just that some other work needs to be done before this can be merged.

2021-03-25 02:33 UTC, huan commented
@simonepri I have merged the #14 because that improvement will not breaking anything.

However, the Node version 4/6 are removed from the CI testing by that PR.

FYI.

2022-12-13 01:25 UTC, jimmywarting reviewed
update versions

2022-12-13 01:25 UTC, jimmywarting commented on .github/workflows/test-macos.yml
> +        node: [15, 14, 12, 10]
```diff
-        node: [15, 14, 12, 10]
+        node: [14, 16, 18]
```

2022-12-13 01:25 UTC, jimmywarting commented on .github/workflows/test-ubuntu.yml
> +        node: [15, 14, 12, 10]
```diff
-        node: [15, 14, 12, 10]
+        node: [14, 16, 18]
```

2022-12-13 01:25 UTC, jimmywarting commented on .github/workflows/test-windows.yml
> +        node: [15, 14, 12, 10]
```diff
-        node: [15, 14, 12, 10]
+        node: [14, 16, 18]
```

2022-12-13 01:25 UTC, jimmywarting commented on index.js
> +const util = require('util');
```diff
-const util = require('util');
+const util = require('node:util');
```

2022-12-13 01:25 UTC, jimmywarting commented on package.json
> +    "node": ">= 10"
```diff
-    "node": ">= 10"
+    "node": ">= 14"
```

2022-12-13 08:47 UTC, Kikobeats commented
Applied suggestions.

Can you take care about this PR? It's open for more than one year.

2022-12-13 11:49 UTC, jimmywarting commented
> Can you take care about this PR?

Sry, can't... Don't have access to this repo

2022-12-13 11:50 UTC, jimmywarting approved these changes

2022-12-13 19:01 UTC, huan requested changes
Thanks for continue improving this PR!

Could you please bump the minor version to the next one (`0.6.0` -> `0.7.0`) so that we can make this change not affect the previous version users?

2022-12-14 08:53 UTC, Kikobeats commented
I prefer to don't bump numbers in a PR; That's a thing can be done after merge the PR.

It looks like nobody has the ability to move this forward, so pinging @simonepri

2024-12-12 11:11 UTC, MikeMcC399 commented
@Kikobeats 

For some reason your PR has remained open without being merged or rejected. In the meantime Node.js versions have moved on.

- I've submitted PR #25 to update the Node.js versions. This would replace some of the changes in this PR. I did not make any changes to `index.js` or `package.json`, so these proposed changes would still be relevant.

2024-12-12 18:33 UTC, Kikobeats commented
closing since authors are not interested

2024-12-12 18:33 UTC, closed without merging